SELECT DISTINCT SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 1
OFFSET 1;
SELECT * 
FROM EMPLOYEES
WHERE SALARY =	(SELECT DISTINCT SALARY
				FROM EMPLOYEES
				ORDER BY SALARY DESC
				LIMIT 1
				OFFSET 1
              );
SELECT *
FROM EMPLOYEES
WHERE SALARY=	(SELECT MAX(SALARY)
				FROM EMPLOYEES 
				WHERE SALARY <  (SELECT MAX(SALARY)
								FROM EMPLOYEES
                                )
				);

SELECT *
FROM EMPLOYEES AS EMP
WHERE SALARY > (SELECT SALARY
				FROM EMPLOYEES AS MGR
                WHERE EMP.MANAGER_ID = MGR.EMPLOYEE_ID
                );

SELECT *
FROM EMPLOYEES AS EMP
WHERE JOB_ID = (SELECT JOB_ID
				FROM EMPLOYEES AS MGR
                WHERE EMP.MANAGER_ID = MGR.EMPLOYEE_ID
                )