USE dummydb;
-- SELF JOIN
SELECT m.FIRST_NAME,e.FIRST_NAME
FROM EMPLOYEES AS e
	JOIN EMPLOYEES AS m
    ON e.EMPLOYEE_ID=m.MANAGER_ID;
-- LEFT JOIN
SELECT DEPARTMENTS.DEPARTMENT_NAME
FROM DEPARTMENTS
	LEFT JOIN EMPLOYEES
    ON DEPARTMENTS.DEPARTMENT_ID=EMPLOYEES.DEPARTMENT_ID
    WHERE EMPLOYEES.DEPARTMENT_ID IS NULL;